// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TemtCash.Main.DAL;

namespace TemtCash.Main.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180419182259_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TemtCash.Main.Domain.Model.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BusinessArea");

                    b.Property<string>("City");

                    b.Property<string>("ClientCode");

                    b.Property<string>("ContactEmail");

                    b.Property<string>("ContactPerson");

                    b.Property<string>("ContactPhone");

                    b.Property<string>("Country");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<bool>("HasStore");

                    b.Property<string>("InvoiceEmail");

                    b.Property<string>("InvoiceFrequency");

                    b.Property<bool>("IsActive");

                    b.Property<DateTime?>("LastInfoUpdateDate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("PrimaryUserId");

                    b.Property<string>("RegNo");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<string>("ZipCode");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("TemtCash.Main.Domain.Model.CompanyLicence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CompanyId");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<bool>("IsActive");

                    b.Property<DateTime?>("LastCheckedDate");

                    b.Property<string>("LicenceKey")
                        .IsRequired();

                    b.Property<int?>("StoreId");

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<DateTime?>("ValidToDate");

                    b.Property<string>("ValidToHash");

                    b.Property<string>("Version");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("StoreId");

                    b.ToTable("CompanyLicences");
                });

            modelBuilder.Entity("TemtCash.Main.Domain.Model.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<int>("CompanyId");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<string>("Email");

                    b.Property<int?>("ExternalId");

                    b.Property<bool>("IsCompany");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Phone");

                    b.Property<string>("RegCode");

                    b.Property<string>("Status");

                    b.Property<int?>("StoreId");

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("StoreId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("TemtCash.Main.Domain.Model.DayPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BeginDate");

                    b.Property<string>("Comment");

                    b.Property<int>("CompanyId");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<float>("DayBeginSum");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<DateTime?>("EndDate");

                    b.Property<int?>("ExternalId");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<int>("StoreId");

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("StoreId");

                    b.ToTable("DayPeriodItems");
                });

            modelBuilder.Entity("TemtCash.Main.Domain.Model.InfoChannelMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<string>("Message")
                        .IsRequired();

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<bool?>("Visible");

                    b.Property<bool>("VisibleForAll");

                    b.Property<DateTime?>("VisibleUntil");

                    b.HasKey("Id");

                    b.ToTable("InfoChannelMessages");
                });

            modelBuilder.Entity("TemtCash.Main.Domain.Model.InfoChannelMessageProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("InfoChannelMessageId");

                    b.Property<string>("Profile");

                    b.HasKey("Id");

                    b.ToTable("InfoChannelMessageProfiles");
                });

            modelBuilder.Entity("TemtCash.Main.Domain.Model.InfoChannelMessageSeen", b =>
                {
                    b.Property<int>("InfoChannelMessageId");

                    b.Property<int>("UserId");

                    b.HasKey("InfoChannelMessageId", "UserId");

                    b.ToTable("InfoChannelMessagesSeen");
                });

            modelBuilder.Entity("TemtCash.Main.Domain.Model.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BonusesUsed");

                    b.Property<float?>("BrutoSum");

                    b.Property<string>("Comment");

                    b.Property<int>("CompanyId");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<int?>("CustomerId");

                    b.Property<DateTime>("Date");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<int?>("Discount");

                    b.Property<DateTime?>("DueDate");

                    b.Property<int?>("ExternalId");

                    b.Property<float?>("GiftCardSum");

                    b.Property<float?>("NetoSum");

                    b.Property<string>("Number");

                    b.Property<int?>("SellerId");

                    b.Property<string>("SellerName");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<int>("StoreId");

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<float?>("VatSum");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StoreId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("TemtCash.Main.Domain.Model.InvoicePaymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<int?>("ExternalId");

                    b.Property<int>("InvoiceId");

                    b.Property<int>("PaymentType");

                    b.Property<float>("Sum");

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoicePaymentTypes");
                });

            modelBuilder.Entity("TemtCash.Main.Domain.Model.InvoiceRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<int?>("Discount");

                    b.Property<float?>("DiscountSum");

                    b.Property<int?>("ExternalId");

                    b.Property<int>("InvoiceId");

                    b.Property<float?>("NetoSum");

                    b.Property<float>("Price");

                    b.Property<int>("ProductId");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<float?>("UsedBonusSum");

                    b.Property<int>("Vat");

                    b.Property<float?>("VatSum");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ProductId");

                    b.ToTable("InvoiceRow");
                });

            modelBuilder.Entity("TemtCash.Main.Domain.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<int>("CompanyId");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<string>("Description");

                    b.Property<bool?>("DissallowDiscount");

                    b.Property<string>("EanCode");

                    b.Property<int?>("ExternalId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<float>("Price");

                    b.Property<int?>("ProductCategoryId");

                    b.Property<string>("ProductType");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<int?>("StoreId");

                    b.Property<int?>("Unit");

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<bool?>("UseProductVat");

                    b.Property<string>("Vat");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("StoreId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("TemtCash.Main.Domain.Model.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CompanyId");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<int?>("ExternalId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int?>("ParentId");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<int?>("StoreId");

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<string>("Vat")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ParentId");

                    b.HasIndex("StoreId");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("TemtCash.Main.Domain.Model.ProductUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CompanyId");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<string>("LangEn");

                    b.Property<string>("LangEt")
                        .IsRequired();

                    b.Property<string>("LangRu");

                    b.Property<int>("Position");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("ProductUnits");
                });

            modelBuilder.Entity("TemtCash.Main.Domain.Model.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<int>("CompanyId");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("TemtCash.Main.Domain.Model.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BankAccount");

                    b.Property<string>("BankIban");

                    b.Property<string>("BankSwift");

                    b.Property<string>("Comment");

                    b.Property<int>("CompanyId");

                    b.Property<string>("CompanyRegNumber");

                    b.Property<string>("CompanyVatNumber");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<int>("DeadlineDays");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<string>("Email");

                    b.Property<bool>("IsPerson");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Phone");

                    b.Property<string>("Skype");

                    b.Property<string>("Status");

                    b.Property<string>("SupType");

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("TemtCash.Main.Domain.Model.WarehouseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Amount");

                    b.Property<int>("CompanyId");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<DateTime>("Date");

                    b.Property<int?>("DeletedBy");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<int?>("ExternalId");

                    b.Property<int?>("ProductId");

                    b.Property<float>("PurchacePrice");

                    b.Property<int>("StoreId");

                    b.Property<int?>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StoreId");

                    b.ToTable("WarehouseItems");
                });

            modelBuilder.Entity("TemtCash.Main.Domain.Model.CompanyLicence", b =>
                {
                    b.HasOne("TemtCash.Main.Domain.Model.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TemtCash.Main.Domain.Model.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId");
                });

            modelBuilder.Entity("TemtCash.Main.Domain.Model.Customer", b =>
                {
                    b.HasOne("TemtCash.Main.Domain.Model.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TemtCash.Main.Domain.Model.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId");
                });

            modelBuilder.Entity("TemtCash.Main.Domain.Model.DayPeriod", b =>
                {
                    b.HasOne("TemtCash.Main.Domain.Model.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TemtCash.Main.Domain.Model.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TemtCash.Main.Domain.Model.Invoice", b =>
                {
                    b.HasOne("TemtCash.Main.Domain.Model.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TemtCash.Main.Domain.Model.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("TemtCash.Main.Domain.Model.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TemtCash.Main.Domain.Model.InvoicePaymentType", b =>
                {
                    b.HasOne("TemtCash.Main.Domain.Model.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TemtCash.Main.Domain.Model.InvoiceRow", b =>
                {
                    b.HasOne("TemtCash.Main.Domain.Model.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TemtCash.Main.Domain.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TemtCash.Main.Domain.Model.Product", b =>
                {
                    b.HasOne("TemtCash.Main.Domain.Model.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TemtCash.Main.Domain.Model.ProductCategory", "ProductCategory")
                        .WithMany()
                        .HasForeignKey("ProductCategoryId");

                    b.HasOne("TemtCash.Main.Domain.Model.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId");
                });

            modelBuilder.Entity("TemtCash.Main.Domain.Model.ProductCategory", b =>
                {
                    b.HasOne("TemtCash.Main.Domain.Model.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TemtCash.Main.Domain.Model.ProductCategory", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.HasOne("TemtCash.Main.Domain.Model.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId");
                });

            modelBuilder.Entity("TemtCash.Main.Domain.Model.ProductUnit", b =>
                {
                    b.HasOne("TemtCash.Main.Domain.Model.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TemtCash.Main.Domain.Model.Store", b =>
                {
                    b.HasOne("TemtCash.Main.Domain.Model.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TemtCash.Main.Domain.Model.Supplier", b =>
                {
                    b.HasOne("TemtCash.Main.Domain.Model.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TemtCash.Main.Domain.Model.WarehouseItem", b =>
                {
                    b.HasOne("TemtCash.Main.Domain.Model.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TemtCash.Main.Domain.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("TemtCash.Main.Domain.Model.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
